// <auto-generated />
namespace StoresManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TableRealationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableRealationships));
        
        string IMigrationMetadata.Id
        {
            get { return "202002092130050_TableRealationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
